version: '3.8'

services:
  school-cream:
    build: .
    container_name: school-cream-app
    restart: unless-stopped
    
    # 环境变量
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models
      - OUTPUT_PATH=/app/output
      - CONF_THRESHOLD=0.5
      - MAX_DET=100
      - UPDATE_INTERVAL=0.1
    
    # 端口映射
    ports:
      - "8080:8080"
    
    # 数据卷挂载
    volumes:
      - ./models:/app/models:ro  # 模型文件（只读）
      - ./output:/app/output     # 输出文件
      - ./config:/app/config:ro  # 配置文件（只读）
      - ./logs:/app/logs         # 日志文件
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11转发（如果需要GUI）
    
    # 设备访问（如果需要GPU）
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    # 网络配置
    networks:
      - school-network
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import torch; import cv2; import mediapipe; print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    
    # 依赖服务
    depends_on:
      - redis
      - nginx
    
    # 启动命令
    command: >
      python main.py 
      --registry_url http://nginx:80/api/courses
      --max_frames 10000

  # Redis缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: school-cream-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - school-network
    command: redis-server --appendonly yes

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: school-cream-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - school-network
    depends_on:
      - school-cream

  # 监控服务（可选）
  prometheus:
    image: prom/prometheus:latest
    container_name: school-cream-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - school-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana可视化（可选）
  grafana:
    image: grafana/grafana:latest
    container_name: school-cream-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - school-network
    depends_on:
      - prometheus

# 网络配置
networks:
  school-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 数据卷
volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
